/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              sowaka: {
                bg: '#FDFCF9',
                card: '#FFFFFF',
                border: '#EAE4DF',
                primary: '#A6513A',
                primaryHover: '#8C402B',
                text: '#382B26',
                textMuted: '#786962',
              },
              "outline-variant": "#dcc1ba",
              "on-surface": "#1b1c19",
              "inverse-surface": "#30312e",
              "error": "#ba1a1a",
              "surface-container": "#f0eee9",
              "error-container": "#ffdad6",
              "surface-dim": "#dbdad5",
              "tertiary": "#743b26",
              "on-primary-fixed-variant": "#7c2d15",
              "on-tertiary-container": "#ffd7c9",
              "tertiary-fixed": "#ffdbcf",
              "tertiary-fixed-dim": "#ffb59b",
              "on-secondary-fixed": "#191c1a",
              "on-error-container": "#93000a",
              "outline": "#89726c",
              "secondary-container": "#e1e3e0",
              "on-tertiary-fixed-variant": "#6f3722",
              "on-background": "#1b1c19",
              "surface-tint": "#9b442a",
              "on-error": "#ffffff",
              "on-primary": "#ffffff",
              "on-secondary": "#ffffff",
              "inverse-on-surface": "#f2f1ec",
              "inverse-primary": "#ffb5a0",
              "primary-fixed": "#ffdbd1",
              "on-primary-container": "#ffd7cc",
              "tertiary-container": "#91523b",
              "primary": "#823119",
              "surface-variant": "#e4e2dd",
              "background": "#fbf9f4",
              "secondary-fixed": "#e1e3e0",
              "primary-fixed-dim": "#ffb5a0",
              "surface-container-low": "#f5f3ee",
              "primary-container": "#a1482e",
              "surface-container-highest": "#e4e2dd",
              "on-secondary-fixed-variant": "#444745",
              "surface-container-lowest": "#ffffff",
              "on-primary-fixed": "#3b0900",
              "on-secondary-container": "#626563",
              "on-tertiary": "#ffffff",
              "secondary-fixed-dim": "#c5c7c4",
              "surface": "#fbf9f4",
              "surface-container-high": "#eae8e3",
              "on-tertiary-fixed": "#380d00",
              "secondary": "#5c5f5d",
              "surface-bright": "#fbf9f4",
              "on-surface-variant": "#55423d"
          },
          "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
          },
          "spacing": {
              "stack-md": "24px",
              "stack-lg": "48px",
              "stack-sm": "8px",
              "container-max": "1280px",
              "unit": "8px",
              "margin-mobile": "16px",
              "gutter": "24px",
              "margin-desktop": "40px"
          },
          "fontFamily": {
              "label-md": ["Hanken Grotesk"],
              "body-lg": ["Hanken Grotesk"],
              "headline-lg-mobile": ["Vollkorn"],
              "headline-xl": ["Vollkorn"],
              "headline-lg": ["Vollkorn"],
              "body-md": ["Hanken Grotesk"],
              "headline-md": ["Vollkorn"],
              "serif": ['Playfair Display', 'serif']
          },
          "fontSize": {
              "label-md": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}],
              "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "headline-lg-mobile": ["28px", {"lineHeight": "1.2", "fontWeight": "700"}],
              "headline-xl": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
              "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700"}],
              "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
              "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "700"}]
          }
      }
  },
  plugins: [],
}
